import type {Metadata} from "next";
import Link from "next/link";
import {Inter} from "next/font/google";
import "./globals.css";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Stackbuld Frontend Assessment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen bg-black bg-opacity-90 flex justify-center items-center">
          <div className="w-9/12">
            <header className="p-4 bg-gray-800 text-white">
              <Link href="/products">
                <h1 className="text-2xl">STACKBULD ASSESSMENT</h1>
              </Link>
            </header>
            <main className="bg-gray-400">{children}</main>
            <footer className="p-4 bg-gray-800 text-white text-center">
              <p>&copy; 2024 Stackbuld Assessment</p>
            </footer>
          </div>
        </div>
      </body>
    </html>
  );
}
